// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeadkAI2gMjv050sgbS5cVSllfharbNQE',
    appId: '1:699255219155:web:380b905e92c97a50c70526',
    messagingSenderId: '699255219155',
    projectId: 'faduapp',
    authDomain: 'faduapp.firebaseapp.com',
    storageBucket: 'faduapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8v_Hmh7SJjphU6kdTSOZy3p_yL-EtrY',
    appId: '1:699255219155:android:d0ec83598d36fb96c70526',
    messagingSenderId: '699255219155',
    projectId: 'faduapp',
    storageBucket: 'faduapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIp-E8jKWzGi0f2KO5pf9Lu5Fbmu0wAdc',
    appId: '1:699255219155:ios:f7cd2327346c31d8c70526',
    messagingSenderId: '699255219155',
    projectId: 'faduapp',
    storageBucket: 'faduapp.appspot.com',
    iosClientId: '699255219155-g01brbg5s9mr57oqv63pq82jqj4od1f4.apps.googleusercontent.com',
    iosBundleId: 'gd.rf.wwitdev.fadu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIp-E8jKWzGi0f2KO5pf9Lu5Fbmu0wAdc',
    appId: '1:699255219155:ios:f7cd2327346c31d8c70526',
    messagingSenderId: '699255219155',
    projectId: 'faduapp',
    storageBucket: 'faduapp.appspot.com',
    iosClientId: '699255219155-g01brbg5s9mr57oqv63pq82jqj4od1f4.apps.googleusercontent.com',
    iosBundleId: 'gd.rf.wwitdev.fadu',
  );
}
